sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-098l
        - $HOME/ossl-100t

matrix:
    include:
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=docs CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
    webhooks:
        - https://buildtimetrend.herokuapp.com/travis
