sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py33 OPENSSL=0.9.8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
    webhooks:
        - https://buildtimetrend.herokuapp.com/travis
