language: c
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
sudo: false
addons:
    apt:
        sources:
            - deadsnakes
            - pypy
        packages:
            - libenchant-dev
            - python2.6
            - python2.6-dev
            - python2.7
            - python2.7-dev
            - python3.2
            - python3.2-dev
            - python3.3
            - python3.3-dev
            - python3.4
            - python3.4-dev
            - pypy
            - pypy-dev
env:
    matrix:
        - TOXENV=py26
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=pypy
        - TOXENV=pypy3
        - TOXENV=py26 OPENSSL=0.9.8
        - TOXENV=py27 OPENSSL=0.9.8
        - TOXENV=py32 OPENSSL=0.9.8
        - TOXENV=py33 OPENSSL=0.9.8
        - TOXENV=py34 OPENSSL=0.9.8
        - TOXENV=pypy OPENSSL=0.9.8
        - TOXENV=pypy3 OPENSSL=0.9.8
        - TOXENV=docs
        - TOXENV=pep8
        - TOXENV=py3pep8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - source ~/.venv/bin/activate && coveralls

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
    webhooks:
        - https://buildtimetrend.herokuapp.com/travis

matrix:
    exclude:
        - os: linux
          env: TOXENV=pypy OPENSSL=0.9.8
        - os: linux
          env: TOXENV=py34 OPENSSL=0.9.8
        - os: linux
          env: TOXENV=py33 OPENSSL=0.9.8
        - os: linux
          env: TOXENV=py32 OPENSSL=0.9.8
        - os: linux
          env: TOXENV=py27 OPENSSL=0.9.8
        - os: linux
          env: TOXENV=py26 OPENSSL=0.9.8
        # excluding pypy3 from linux configs until the ubuntu ppa has pypy3 available.
        - os: linux
          env: TOXENV=pypy3
        - os: linux
          env: TOXENV=pypy3 OPENSSL=0.9.8
        - os: osx
          compiler: gcc
        - os: osx
          env: TOXENV=pep8
          compiler: clang
        - os: osx
          env: TOXENV=py3pep8
          compiler: clang

        - os: linux
          env: TOXENV=docs
          compiler: clang
        - os: linux
          env: TOXENV=pep8
          compiler: clang
        - os: linux
          env: TOXENV=py3pep8
          compiler: clang
