jobs:
- job: 'mac'
  pool:
    vmImage: 'macOS 10.13'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        TOXENV: py27
      Python37:
        python.version: '3.7'
        TOXENV: py37
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: brew install openssl@1.1
    displayName: 'Install OpenSSL'

  - script: pip install tox codecov
    displayName: 'Install tox & codecov'

  - script: git clone https://github.com/google/wycheproof
    displayName: 'Clone wycheproof'

  - script: |
      set -e
      set -x
      
      CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1 \
        LDFLAGS="/usr/local/opt/openssl\\@1.1/lib/libcrypto.a /usr/local/opt/openssl\\@1.1/lib/libssl.a" \
        CFLAGS="-I/usr/local/opt/openssl\\@1.1/include -Werror -Wno-error=deprecated-declarations -Wno-error=incompatible-pointer-types-discards-qualifiers -Wno-error=unused-function -Wno-error=unused-command-line-argument -mmacosx-version-min=10.9" \
        tox -r --  --color=yes --wycheproof-root=wycheproof
    displayName: 'Run tests'

  - script: codecov
    displayName: 'Submit coverage'
    condition: succeeded()
