jobs:
- job: 'mac'
  pool:
    vmImage: 'macOS 10.13'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: brew install openssl@1.1
    displayName: 'Install OpenSSL'

  - script: pip install tox
    displayName: 'Install tox'

  - script: git clone https://github.com/google/wycheproof
    displayName: 'Clone wycheproof'
    
  - script: |
      set -x
      set -e
      if [[ "$PYTHON_VERSION" == "2.7" ]]; then
        export TOXENV=py27
      elif [[ "PYTHON_VERSION" == "3.7" ]]; then
        export TOXENV=py37
      fi
      printenv
