name: Upload Coverage
description: Upload coverage to codecov

inputs:
  name:
    description: "Job name"
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        COVERAGE_UUID=$(python3 -c "import uuid; print(uuid.uuid4())")
        echo "COVERAGE_UUID=${UUID}" >> $GITHUB_ENV
        mv .coverage .coverage.${COVERAGE_UUID}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ env.COVERAGE_UUID }}
        path: ".coverage.*"
        if-no-files-found: ignore
