name: Upload Coverage
description: Upload coverage to codecov

inputs:
  name:
    description: "Job name"
    required: true

runs:
  using: "composite"

  steps:
    - uses: codecov/codecov-action@v2.1.0
      with:
        name: ${{ inputs.name }}
        verbose: true
