name: Upload Coverage
description: Upload coverage

inputs:
  name:
    description: "Job name (must be unique within workflow)"
    required: true

runs:
  using: "composite"

  steps:
    - run: coverage xml
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ inputs.name }}
        path: |
            coverage.xml
            rust-cov.lcov
