- hosts: all
  tasks:

    - name: Install tox
      include_role:
        name: ensure-tox

    - name: Install required packages
      package:
        name:
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
      become: yes
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install required packages
      package:
        name:
          - redhat-rpm-config
          - gcc
          - libffi-devel
          - openssl-devel
          - python3-devel
          - python2-devel
      become: yes
      when: ansible_distribution == 'CentOS'

    - name: Clone wycheproof
      git:
        repo: https://github.com/google/wycheproof
        dest: "{{ ansible_facts.env['HOME'] }}/wycheproof"
        depth: 1

    - name: Ridiculous bcrypt test part two
      shell: |
        set -xe
        curl -O https://f001.backblazeb2.com/file/dropshare-fenrir/bcrypt-good-cp36-abi3-manylinux2014_aarch64.whl
        python3 -m venv venv
        venv/bin/python -c "import os; print(os.sysconf('SC_PAGESIZE'))"
        venv/bin/pip install -U pip wheel
        mv bcrypt-good-cp36-abi3-manylinux2014_aarch64.whl bcrypt-3.2.0-cp36-abi3-manylinux2014_aarch64.whl
        venv/bin/pip install bcrypt-3.2.0-cp36-abi3-manylinux2014_aarch64.whl
        venv/bin/python -c "import bcrypt; password = b'super secret password';hashed = bcrypt.hashpw(password, bcrypt.gensalt());bcrypt.checkpw(password, hashed)"

    - name: Ridiculous bcrypt test part one
      shell: |
        set -xe
        python3 -m venv venv2
        venv2/bin/python -c "import os; print(os.sysconf('SC_PAGESIZE'))"
        venv2/bin/pip install -U pip wheel
        venv2/bin/pip install -U bcrypt
        venv2/bin/python -c "import bcrypt; password = b'super secret password';hashed = bcrypt.hashpw(password, bcrypt.gensalt());bcrypt.checkpw(password, hashed)"
